### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by JLi69** [Birb-Games/birb-run#7]
So as we are planning on at least making this into a practice project on how to use Godot collaboratively, I believe that we should at least try to outline what we wish along with some goals - it would also be nice to also come up with some general standards that we should try to hold ourselves to in order to keep maintenance of this project somewhat smooth.

So here are my ideas for what we should try to implement into this game (feel free to leave feedback and also add ideas):

## Stuff we should have:
- [x] Multiple (somewhat decently designed) levels
- [x] Sidescrolling, as the player moves across the screen we should be able to see more of the game level
- [x] Power ups - some ideas include jump boost and the ability to shoot bullets
- [x] A couple of enemy types
- [x] A main menu and pause screen
- [x] More tiles and art
- [x] Sound effects
- [x] Build this for Windows and Linux (so we can share with our friends :P)
- [x] Figure out how to build a game for the web and publish onto itch.io

## Stuff we maybe can add:
- [x] Perhaps levels are locked until you complete the previous one and therefore we can look into figuring out how to implement some basic save data (this can then also go with the speedrunning idea where we also store the best times for each level)
- [ ] Perhaps a timer to measure how fast you complete a level? Maybe we can make this into a speedrunning game?

Anyway, let me know of what you guys think.

Oh yeah, I think we should also release this as an open-source game so we should also probably decide on a license.
